# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 147d4f9b3df9c3d8e8c63f89c58a8673662cc16443dd4a77b3d84c6ca490143b8c6b3dfa7633b044a5b55801029c2eb025906d36708c9e941ed3bc58cf1fe782

test:
  secret_key_base: b06d986c73224723717b7a817142d815af892393f5b0d3cbf9d6afaea10698e9b42e99bc9abddb2c3962982d683fcff8a7186368f5f6e9c64799b8608389630e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
